import importlib.util
import json
import re
import struct
import subprocess
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[2]
GEN = ROOT / "tools" / "gen" / "params_gen.py"
FIXTURES = ROOT / "tests" / "fixtures" / "params"
_spec = importlib.util.spec_from_file_location("params_gen", GEN)
gen = importlib.util.module_from_spec(_spec)
sys.modules["params_gen"] = gen
_spec.loader.exec_module(gen)

GOOD = {
    "type": "f32",
    "value": "0.75",
    "unit": "kg",
    "method": "scenario",
    "source": '"test data"',
    "sigma": "0.01",
}


def entry_yaml(name, **fields):
    body = ", ".join(f"{k}: {v}" for k, v in fields.items() if v is not None)
    return f"{name}: {{{body}}}\n"


def good_entry(name="p", **overrides):
    """One YAML entry; override values are raw YAML text, None drops the field."""
    fields = {**GOOD, **{k: (v if v is None or isinstance(v, str) else repr(v)) for k, v in overrides.items()}}
    return entry_yaml(name, **fields)


def run_gen(tmp_path, *sources, out="out"):
    args = [sys.executable, str(GEN)]
    for kind, path in sources:
        args += [f"--{kind}", str(path)]
    args += ["--out-dir", str(tmp_path / out)]
    return subprocess.run(args, capture_output=True, text=True, check=False)


def write(tmp_path, text, name="src.yaml"):
    p = tmp_path / name
    p.write_text(text)
    return p


def fixture_sources():
    return [("card", FIXTURES / "l0_card.yaml"), ("register", FIXTURES / "l0_register.yaml")]


def read_out(tmp_path, out="out"):
    d = tmp_path / out
    return {f: (d / f).read_bytes() for f in ("param_ids.hpp", "param_defaults.cpp", "params_manifest.json")}


def header_hash(header: str) -> int:
    return int(re.search(r"kParamSchemaHash = 0x([0-9a-f]{16})ULL", header).group(1), 16)


def refused(tmp_path, text, *needles):
    r = run_gen(tmp_path, ("card", write(tmp_path, text)))
    assert r.returncode == 1, r.stdout + r.stderr
    for needle in needles:
        assert needle in r.stderr, r.stderr
    assert not (tmp_path / "out").exists(), "a refused run must write nothing"
    return r


def test_fixture_generates(tmp_path):
    r = run_gen(tmp_path, *fixture_sources())
    assert r.returncode == 0, r.stderr
    out = read_out(tmp_path)
    assert out["param_ids.hpp"].startswith(b"// Generated by tools/gen/params_gen.py")


@pytest.mark.parametrize("field", ["type", "value", "unit", "method", "source", "sigma"])
def test_missing_field_is_refused(tmp_path, field):
    refused(tmp_path, good_entry("mass", **{field: None}), "mass", f"field '{field}'", "missing")


@pytest.mark.parametrize(
    ("overrides", "field"),
    [
        ({"sigma": "-0.5"}, "sigma"),
        ({"sigma": ".inf"}, "sigma"),
        ({"sigma": ".nan"}, "sigma"),
        ({"sigma": '"0.1"'}, "sigma"),
        ({"sigma": "1e300"}, "sigma"),
        ({"value": ".inf"}, "value"),
        ({"value": "-.inf"}, "value"),
        ({"value": ".nan"}, "value"),
        ({"value": "1e300"}, "value"),
        ({"value": '"0.75"'}, "value"),
        ({"type": "i32", "value": "4.0"}, "value"),
        ({"type": "i32", "value": "2.5"}, "value"),
        ({"type": "i32", "value": str(2**31)}, "value"),
        ({"type": "i32", "value": str(-(2**31) - 1)}, "value"),
        ({"type": "i32", "value": "true"}, "value"),
        ({"type": "f64"}, "type"),
        ({"type": "float"}, "type"),
        ({"method": "guessed"}, "method"),
        ({"method": "Published"}, "method"),
        ({"method": "derived"}, "method"),
        ({"method": '"derived()"'}, "method"),
        ({"source": '""'}, "source"),
        ({"unit": '""'}, "unit"),
    ],
)
def test_bad_field_is_refused(tmp_path, overrides, field):
    refused(tmp_path, good_entry("mass", **overrides), "mass", f"field '{field}'")


def test_unknown_field_is_refused(tmp_path):
    refused(tmp_path, good_entry("mass", origin="default-from-card"), "mass", "field 'origin'")


@pytest.mark.parametrize("name", ["1abc", "_x", "a-b", "a.b", "a b", "int", "class", "a__b", "naïve"])
def test_invalid_enumerator_name_is_refused(tmp_path, name):
    refused(tmp_path, good_entry(json.dumps(name, ensure_ascii=False)), "field 'name'")


def test_duplicate_name_across_files_is_refused(tmp_path):
    a = write(tmp_path, good_entry("mass"), "a.yaml")
    b = write(tmp_path, good_entry("mass"), "b.yaml")
    r = run_gen(tmp_path, ("card", a), ("register", b))
    assert r.returncode == 1
    assert "mass" in r.stderr and "duplicate" in r.stderr and "a.yaml" in r.stderr
    assert not (tmp_path / "out").exists()


def test_duplicate_name_within_a_file_is_refused(tmp_path):
    refused(tmp_path, good_entry("mass") + good_entry("mass"), "duplicate key 'mass'")


def test_no_parameters_is_refused(tmp_path):
    refused(tmp_path, "{}\n", "no parameters")


def test_derived_with_rule_is_accepted_and_keeps_the_rule(tmp_path):
    src = write(tmp_path, good_entry("k", method='"derived(2 * m)"'))
    assert run_gen(tmp_path, ("card", src)).returncode == 0
    cpp = read_out(tmp_path)["param_defaults.cpp"].decode()
    assert "ParamMethod::Derived" in cpp and '"2 * m; test data"' in cpp


def test_origin_follows_file_kind(tmp_path):
    a = write(tmp_path, good_entry("a"), "a.yaml")
    b = write(tmp_path, good_entry("b"), "b.yaml")
    assert run_gen(tmp_path, ("card", a), ("register", b)).returncode == 0
    cpp = read_out(tmp_path)["param_defaults.cpp"].decode()
    assert cpp.index("DefaultFromCard") < cpp.index("DefaultFromRegister")


def test_every_method_maps(tmp_path):
    methods = ["published", "measured", "identified", "datasheet", "design-budget", "scenario", "derived(r)"]
    src = write(tmp_path, "".join(good_entry(f"p{i}", method=json.dumps(m)) for i, m in enumerate(methods)))
    assert run_gen(tmp_path, ("card", src)).returncode == 0
    cpp = read_out(tmp_path)["param_defaults.cpp"].decode()
    for name in ("Published", "Measured", "Identified", "Datasheet", "DesignBudget", "Scenario", "Derived"):
        assert f"ParamMethod::{name}" in cpp


def test_exponent_without_dot_is_a_float(tmp_path):
    src = write(tmp_path, good_entry("k", value="1e-6", sigma="1e-7"))
    assert run_gen(tmp_path, ("card", src)).returncode == 0, "1e-6 must be read as a number"


def test_output_is_byte_identical_across_runs(tmp_path):
    assert run_gen(tmp_path, *fixture_sources(), out="one").returncode == 0
    assert run_gen(tmp_path, *fixture_sources(), out="two").returncode == 0
    assert read_out(tmp_path, "one") == read_out(tmp_path, "two")


def test_order_follows_the_sources(tmp_path):
    a = write(tmp_path, good_entry("zeta") + good_entry("alpha"), "a.yaml")
    b = write(tmp_path, good_entry("mid"), "b.yaml")
    assert run_gen(tmp_path, ("card", a), ("register", b)).returncode == 0
    ids = re.findall(r"^  (\w+) = (\d+),$", read_out(tmp_path)["param_ids.hpp"].decode(), re.M)
    assert ids == [("zeta", "0"), ("alpha", "1"), ("mid", "2")]


def hash_of(tmp_path, text, out):
    src = write(tmp_path, text, f"{out}.yaml")
    r = run_gen(tmp_path, ("card", src), out=out)
    assert r.returncode == 0, r.stderr
    return header_hash(read_out(tmp_path, out)["param_ids.hpp"].decode())


def test_schema_hash_changes_on_rename_retype_reunit_not_on_value(tmp_path):
    base = hash_of(tmp_path, good_entry("mass"), "base")
    assert hash_of(tmp_path, good_entry("mass2"), "renamed") != base
    assert hash_of(tmp_path, good_entry("mass", type="i32", value=3), "retyped") != base
    assert hash_of(tmp_path, good_entry("mass", unit="g"), "reunited") != base
    assert hash_of(tmp_path, good_entry("mass", value=123.5, sigma=9.0, source='"other"', method="measured"),
                   "revalued") == base


def test_schema_hash_depends_on_order(tmp_path):
    ab = hash_of(tmp_path, good_entry("a") + good_entry("b"), "ab")
    ba = hash_of(tmp_path, good_entry("b") + good_entry("a"), "ba")
    assert ab != ba


def test_schema_hash_is_the_documented_sha256_prefix(tmp_path):
    import hashlib

    digest = hashlib.sha256(b"mass\x1ff32\x1fkg\x1e").digest()
    assert hash_of(tmp_path, good_entry("mass"), "doc") == int.from_bytes(digest[:8], "big")


def test_float_round_trip_is_exact(tmp_path):
    values = [0.1, 0.033, 1.0e-6, 1.5625e-6, 3.4028234663852886e38, 1.401298464324817e-45, 16777217.0, -0.0, 1.0,
              123456.789, 2.0**-100]
    text = "".join(good_entry(f"v{i}", value=repr(v), sigma="0") for i, v in enumerate(values))
    src = write(tmp_path, text)
    assert run_gen(tmp_path, ("card", src)).returncode == 0
    cpp = read_out(tmp_path)["param_defaults.cpp"].decode()
    literals = re.findall(r"\{\{ParamType::F32, (\S+?)f, 0\}", cpp)
    assert len(literals) == len(values)
    for lit, v in zip(literals, values, strict=True):
        assert "." in lit or "e" in lit, lit
        expected = struct.unpack("<f", struct.pack("<f", v))[0]
        got = struct.unpack("<f", struct.pack("<f", float(lit)))[0]
        assert struct.pack("<f", got) == struct.pack("<f", expected), (lit, v)


def test_integer_valued_float_literal_is_valid_cpp(tmp_path):
    src = write(tmp_path, good_entry("v", value="1", sigma="0"))
    assert run_gen(tmp_path, ("card", src)).returncode == 0
    assert "{{ParamType::F32, 1.0f, 0}, 0.0f," in read_out(tmp_path)["param_defaults.cpp"].decode()


def test_int32_extremes(tmp_path):
    text = good_entry("lo", type="i32", value=-(2**31), sigma="0") + good_entry("hi", type="i32", value=2**31 - 1, sigma="0")
    assert run_gen(tmp_path, ("card", write(tmp_path, text))).returncode == 0
    cpp = read_out(tmp_path)["param_defaults.cpp"].decode()
    assert "-2147483647 - 1" in cpp and "2147483647}" in cpp


def test_manifest_agrees_with_header(tmp_path):
    assert run_gen(tmp_path, *fixture_sources()).returncode == 0
    out = read_out(tmp_path)
    header = out["param_ids.hpp"].decode()
    manifest = json.loads(out["params_manifest.json"])
    enum_body = re.search(r"enum class ParamId : std::uint16_t \{(.*?)\};", header, re.S).group(1)
    ids = [(n, int(i)) for n, i in re.findall(r"(\w+) = (\d+),", enum_body)]
    assert [n for n, _ in ids] == list(manifest["params"])
    assert [i for _, i in ids] == list(range(len(ids)))
    assert manifest["count"] == len(ids) == int(re.search(r"kParamCount = (\d+);", header).group(1))
    assert int(manifest["schema_hash"], 16) == header_hash(header)
    traits = dict(re.findall(r"ParamTraits<ParamId::(\w+)> \{\s*using value_type = ([\w:]+);", header))
    for name, info in manifest["params"].items():
        assert traits[name] == {"f32": "float", "i32": "std::int32_t"}[info["type"]]
    assert manifest["params"]["fixture_motor_count"] == {"id": 1, "type": "i32", "unit": "1"}
    assert manifest["params"]["fixture_drag_ratio"]["unit"] == "1"


def test_manifest_excludes_values(tmp_path):
    a = hash_of(tmp_path, good_entry("mass", value=1.0), "a")
    text_b = json.loads((tmp_path / "a" / "params_manifest.json").read_text())
    assert "value" not in text_b["params"]["mass"] and a == int(text_b["schema_hash"], 16)
