#!/usr/bin/env python3
"""Writes the input fixture of the I-A1 acro bit-identity golden (quad spec 4 L5, decision 0006 "A").

    uv run python tests/regression/quad/L05/unit/rate_bypass/gen_fixture.py [--dir DIR]

Reads reference/rate_bypass_inputs.txt (the L04 T3 inputs) for rate_max, the gains and the tick, and writes
rate_bypass_fixture.txt into DIR (default: reference/, beside the inputs). Python stdlib only; every value is a
function of the constants below, so the output is byte-identical on every host.

One line per execution n:  n t_us g0 g1 g2 gyro_valid s0 s1 s2 f0 f1 f2 q0 q1 q2 a0 a1 a2
  t_us         the sample stamp, floor(n * rate_loop_divisor * num / den) microseconds (the T3 stamps: dt alternates
               312 / 313 us against T = 312.5 us)
  g, s         gyro (rad/s) and setpoint (rad/s) per axis, float32 bit patterns (0x%08x)
  gyro_valid   0 or 1
  f            the L3 saturation flag per axis (0 or 1), passed to record_allocation
  q, a         the requested and the achieved torque per axis (N*m), float32 bit patterns, passed to record_allocation
"""
import argparse
import os
import struct

HERE = os.path.dirname(os.path.abspath(__file__))
MASK = (1 << 64) - 1
AXES = ("roll", "pitch", "yaw")

# Scenario test values (each a choice of the fixture, not a parameter):
SEED = 0x4D41525635524154  # "MARV5RAT": the generator state; any nonzero value would do
EXECUTIONS = 512  # long enough for several setpoint steps, freeze episodes and five fault events
HOLD = 32  # executions a setpoint is held before the next random draw (a stepwise command)
GYRO_SCALE = 0.25  # the gyro is uniform in +-GYRO_SCALE rate_max: arbitrary but inside the rate range
FLAG_ABOVE = 0.0  # the saturation flag is set where the draw exceeds this: about half the executions
ROUNDING_BELOW = -1.0 / 3.0  # a draw below this sets achieved == requested (the rounding case): about a third
SHORTFALL = 0.5  # otherwise achieved = SHORTFALL * requested: a shortfall far above the rounding bound
# Fault events, index -> kind: a NaN gyro, a cleared GyroValid, a NaN setpoint, then an infinite gyro at the seed
# execution that follows it (301 follows 300), and a NaN setpoint again.
FAULTS = {100: "gyro_nan_pitch", 200: "gyro_invalid", 300: "sp_nan_yaw", 301: "gyro_inf_roll", 400: "sp_nan_roll"}


def f32_bits(x):
    return struct.unpack("<I", struct.pack("<f", x))[0]


F32_NAN = 0x7FC00000
F32_INF = 0x7F800000


class Rng:
    """xorshift64*: integer arithmetic only, so the stream is reproducible everywhere."""

    def __init__(self, seed):
        self.x = seed

    def next_u64(self):
        x = self.x
        x ^= x >> 12
        x ^= (x << 25) & MASK
        x ^= x >> 27
        self.x = x
        return (x * 0x2545F4914F6CDD1D) & MASK

    def uniform(self):
        """Uniform in [-1, 1): 24 random bits, exact in binary32."""
        return (self.next_u64() >> 40) / float(1 << 23) - 1.0


def read_inputs(path):
    out = {}
    for line in open(path):
        line = line.split("#")[0].split()
        if len(line) == 2:
            out[line[0]] = float.fromhex(line[1]) if "0x" in line[1] else float(line[1])
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dir", default=os.path.join(HERE, "reference"))
    args = ap.parse_args()
    v = read_inputs(os.path.join(HERE, "reference", "rate_bypass_inputs.txt"))
    div, num, den = int(v["rate_loop_divisor"]), int(v["tick_period_num_us"]), int(v["tick_period_den"])
    rate_max = v["rate_max_roll"]
    kp = [v["rate_kp_" + a] for a in AXES]

    rng = Rng(SEED)
    sp = [0.0, 0.0, 0.0]
    lines = [
        "# I-A1 fixture: the scripted inputs of the acro bit-identity golden. Generated by gen_fixture.py (README.md).",
        "# n t_us g0 g1 g2 gyro_valid s0 s1 s2 f0 f1 f2 q0 q1 q2 a0 a1 a2 (floats: binary32 bit patterns)",
        f"executions {EXECUTIONS}",
    ]
    for n in range(EXECUTIONS):
        if n % HOLD == 0:
            sp = [rng.uniform() * rate_max for _ in range(3)]
        g = [f32_bits(GYRO_SCALE * rate_max * rng.uniform()) for _ in range(3)]
        s = [f32_bits(x) for x in sp]
        flag = []
        req = []
        ach = []
        for a in range(3):
            flag.append(1 if rng.uniform() > FLAG_ABOVE else 0)
            # The requested torque is of the size of the proportional term at full rate: kp * rate_max.
            q = struct.unpack("<f", struct.pack("<f", kp[a] * rate_max * rng.uniform()))[0]
            rounding = rng.uniform() < ROUNDING_BELOW
            req.append(f32_bits(q))
            ach.append(f32_bits(q if rounding else SHORTFALL * q))
        valid = 1
        kind = FAULTS.get(n)
        if kind == "gyro_nan_pitch":
            g[1] = F32_NAN
        elif kind == "gyro_invalid":
            valid = 0
        elif kind == "sp_nan_yaw":
            s[2] = F32_NAN
        elif kind == "gyro_inf_roll":
            g[0] = F32_INF
        elif kind == "sp_nan_roll":
            s[0] = F32_NAN
        t_us = (n * div * num) // den
        cols = [str(n), str(t_us)]
        cols += [f"0x{b:08x}" for b in g] + [str(valid)]
        cols += [f"0x{b:08x}" for b in s] + [str(f) for f in flag]
        cols += [f"0x{b:08x}" for b in req] + [f"0x{b:08x}" for b in ach]
        lines.append(" ".join(cols))
    os.makedirs(args.dir, exist_ok=True)
    with open(os.path.join(args.dir, "rate_bypass_fixture.txt"), "w") as f:
        f.write("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
