// Writes the I-A1 acro golden: the scripted scenario of acro_scenario.hpp run through RateLoop<float>::execute of the
// fw/rate that this file is compiled against. regenerate.sh compiles it against fw/rate at tag quad-L4-pass. Not part
// of the build.
//
//   golden_gen <inputs> <fixture> <golden out>
#include <cstdio>
#include <cstdlib>
#include <fstream>
#include <string>
#include <vector>

#include "acro_scenario.hpp"

namespace marv::rate {
template class RateLoop<float>;  // the tag's header declares these extern; instantiated here so no library is linked
template ConfigError validate<float>(const RateConfig<float>&) noexcept;
namespace detail {
void panic_period() noexcept { std::abort(); }
}  // namespace detail
}  // namespace marv::rate

int main(int argc, char** argv) {
  if (argc != 4) {
    std::fprintf(stderr, "usage: golden_gen <inputs> <fixture> <golden out>\n");
    return 2;
  }
  marv::rate::RateConfig<float> cfg;
  std::vector<marv::l5_rate_bypass::Step> steps;
  if (!marv::l5_rate_bypass::read_config(argv[1], cfg) || !marv::l5_rate_bypass::read_fixture(argv[2], steps)) {
    std::fprintf(stderr, "golden_gen: cannot read the inputs or the fixture\n");
    return 1;
  }
  std::ofstream f(argv[3]);
  f << "# I-A1 golden: the acro torque, fault and integrator bit patterns of RateLoop<float>::execute at tag quad-L4-pass.\n"
       "# Generated by regenerate.sh (README.md); do not edit.\n"
       "# n u0 u1 u2 fault_active fault_latched fault_count i0 i1 i2\n"
    << marv::l5_rate_bypass::run_acro(cfg, steps);
  return f ? 0 : 1;
}
