#!/usr/bin/env python3
"""Vehicle SDF generator (core contracts 2.1 rule 2 and section 6, quad spec L1).

  gen_sdf.py --card <vehicle>.yaml --out-dir <dir> [--root <repo root>]

Writes <dir>/<vehicle>.sdf (build directory only, never committed) from the linted card; an unlinted card generates
nothing (exit 1, findings on stderr, no file written). See gen_plant_config.py for the refusal rules.

  SDFormat version 1.11: the specification version of sdformat14, the library gz-sim 8 (Gazebo Harmonic) builds on.
  One model, one link `base_link`. Link origin at the centre of mass: the link pose and the inertial pose are zero
  (core section 6), so a wrench applied at the link origin acts at the CM.
  <inertial> carries the card's mass and ixx, iyy, izz with ixy = ixz = iyz = 0. The card frame is FRD and Gazebo's is
  FLU; they differ by a 180 degree rotation about x, which flips the signs of y and z. A diagonal inertia tensor
  I = diag(a, b, c) becomes R I R^T with R = diag(1, -1, -1), which is I again, so the diagonal is unchanged.
  The <plugin> element is the plugin configuration from gen_plant_config.py (provisional plugin names).
  No visual or collision geometry (Q-D1, and the L2 host, own that). World gravity is a world property and is zero
  in every host (core section 6); nothing here sets it.
"""

from __future__ import annotations

import argparse
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

import gen_plant_config as gpc
import schema

SDF_VERSION = "1.11"
LINK_NAME = "base_link"
ZERO_POSE = "0 0 0 0 0 0"
INERTIA_AXES = ("ixx", "iyy", "izz")
INERTIA_OFF_DIAGONAL = ("ixy", "ixz", "iyz")
OFF_DIAGONAL_VALUE = "0"


def sdf_element(card, cfg, units):
    sdf = ET.Element("sdf", {"version": SDF_VERSION})
    model = ET.SubElement(sdf, "model", {"name": card["vehicle"]})
    model.append(ET.Comment(
        f" Generated by tools/card/gen_sdf.py from the vehicle card {card['vehicle']}. SDFormat {SDF_VERSION} "
        "(sdformat14, the library of gz-sim 8). The link origin is the centre of mass. The card is FRD and this "
        "file is FLU; a diagonal inertia is unchanged by that 180 degree rotation about x. "))
    link = ET.SubElement(model, "link", {"name": LINK_NAME})
    gpc.text_element(link, "pose", ZERO_POSE)
    inertial = ET.SubElement(link, "inertial")
    gpc.text_element(inertial, "pose", ZERO_POSE)
    gpc.text_element(inertial, "mass", repr(cfg["mass_kg"]))
    inertia = ET.SubElement(inertial, "inertia")
    diag = card["inertia_diag"]["value"]
    for tag, value in zip(INERTIA_AXES, diag):
        gpc.text_element(inertia, tag, repr(float(value)))
    for tag in INERTIA_OFF_DIAGONAL:
        gpc.text_element(inertia, tag, OFF_DIAGONAL_VALUE)
    model.append(gpc.plugin_element(cfg, units, card))
    return sdf


def generate(card_path, root=gpc.ROOT):
    """Return (file name, text), or raise gpc.GenError."""
    card, profile = gpc.load_linted(card_path, root)
    if card["inertia_diag"]["value"] == schema.UNKNOWN:
        gpc.refuse(card_path, "inertia_diag", f"value is {schema.UNKNOWN}; the SDF needs it")
    cfg, units = gpc.config_from(card, profile, card_path, root)
    text = '<?xml version="1.0"?>\n' + gpc.to_text(sdf_element(card, cfg, units))
    return f"{card['vehicle']}.sdf", text


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--card", required=True, metavar="FILE")
    ap.add_argument("--out-dir", required=True, metavar="DIR")
    ap.add_argument("--root", default=str(gpc.ROOT), help="repository root for resolving sensor_profile")
    args = ap.parse_args(argv)
    try:
        name, text = generate(args.card, args.root)
    except gpc.GenError as e:
        for line in e.lines:
            print(line, file=sys.stderr)
        return 1
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / name).write_text(text, encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
