"""The stage (e) bias delta (tools/sim/l6_bias_delta.py) and the nonlinear hooks of tools/sim/l6_ff_eval.py (decision 0019
ruling 6; the noise suite design memo of 2026-10-04, section 2, commit C5), per push.

The hooks are inert when off: test_l6_ff_eval.py reproduces card_worst.txt byte for byte with them in place (and sweep.txt
was regenerated byte for byte by its own command at C5). Here:
  (1) the corner rules: gyro_bias is imu_corner_config's s_i x bound, the accel signs give no gyro bias; clock_error gives
      0012's realised outward values (question E entry, m = 1) to their printed digits;
  (2) the model's L4 mode (run with setpoints) is l6_ff_eval.simulate bit for bit on the acro script (the T4e sensor,
      PID+FF+lag, the card plant with w x J w), hooks off and all three on; on step_roll each hook alone changes
      simulate's run and a zero bias equals no bias;
  (3) the model's L5 mode on the design plant reproduces recovery_model.member_run bit for bit (the recover_tumble and
      recover_inverted starts, the card member and a box corner; control: the card member against the corner's
      reference), and attitude_t3_oracle.simulate's golden channels (th, om) and its yaw lock bit for bit (step_roll,
      yaw_release, short segments; control: the sticks one execution late);
  (4) the nonlinear plant (coupling, FF and DShot off) against the design plant on the L5 step_roll script: within one
      tick of the design response's largest change (TICK_RULE); control: the design plant at J x FINE_FACTOR breaks it;
  (5) check (i), L4: (a) with FF off the bias is exactly a setpoint offset of -b from the seed execution on:
      simulate(bias b) equals simulate(setpoints - b) bit for bit on step_roll (T4e, the card plant with w x J w, DShot
      rounding); control: with FF on they differ (FF reads the biased rate, memo F-d); (b) the hold at hover (coupling,
      FF and DShot off, the T4e linear sensor): delta = -b s(n) of the T4e linear model (l6_ff_eval.linear_response, s the
      response to a unit setpoint step from the seed execution) within TICK_RULE; control: the linear model at
      J x FINE_FACTOR breaks it;
  (6) check (i), L5: (a) the same identity in the attitude loop (bias b against rate_add = -b), T4e, w x J w, DShot
      rounding; control: FF on; (b) the hold at hover with one gyro axis biased (coupling, FF and DShot off): the
      attitude error's delta ends at b / att_kp within the single-axis law's inverse (offset_bound), roll and yaw;
      control: b / (att_kp x FINE_FACTOR) breaks the bound;
  (7) check (ii): an accel-only corner gives delta = 0 bit for bit (L4 step_roll and an L5 hold, the full model: T4e,
      w x J w, FF on, DShot rounding); control: one gyro sign flipped changes delta.
TICK_RULE (INFERRED): the nonlinear plant applies the torque of the speeds at a tick's end over that tick (marv_plant_step)
where the design plant integrates the motor lag exactly inside it, so the two responses to the same input differ by about
the response's change over one tick; the bound is the largest one-tick change max_n |x(n + 1) - x(n)| / D of the
reference response x (executions are D ticks apart).
"""

import dataclasses
import math
import sys
from pathlib import Path
from unittest import mock

import pytest

ROOT = Path(__file__).resolve().parents[5]
sys.path.insert(0, str(ROOT / "tools" / "sim"))
import l6_bias_delta as bd  # noqa: E402

fe, rm, aor = bd.fe, bd.rm, bd.aor
L4 = ROOT / "scenarios" / "quad" / "L04"

# Labelled test values.
GYRO_CORNER = (1, -1, 1, 0, 0, 0)        # mixed gyro signs, accel 0
ACCEL_CORNER = (0, 0, 0, 1, -1, 1)       # accel only
FLIPPED_CORNER = (-1, -1, 1, 0, 0, 0)    # GYRO_CORNER with the x sign flipped (the control)
QE_PPM = {-1: -70.395044, 1: 70.404957}  # decision 0012, question E entry, m = 1: e in ppm, printed to 6 decimals
QE_HALF_UNIT_PPM = 5e-7                  # half a unit of that sixth decimal
PPM = 1e-6
RECOVERY_EXECUTIONS = 600                # executions of the recovery_model reproduction: the first 0.19 s of the recovery
BOX_MEMBER = (1.0, -1.0)                 # a corner of the tau x J box (J (1 + b_J), tau (1 - b_tau))
STEP_SEGMENT = 300                       # H of the short golden step_roll script (attitude executions)
YAW_SEGMENT = 1500                       # H of the short yaw_release script: long enough for the release's lock
L5_STEP_SEGMENT = 300                    # H of the L5 step_roll script of (4) and of (7)
HOLD_EXECUTIONS = 20000                  # the L5 hold of (6 b): 6.25 s, 20 attitude time constants 1 / att_kp
HOLD_AXES = (0, 2)                       # roll and yaw: the tilt and the yaw form of the law (pitch has roll's form)
L5_IDENTITY_EXECUTIONS = 4000            # the L5 runs of (6 a) and (7): 1.25 s
TAYLOR_DIVISOR = 24                      # 2 asin(x / 2) = x + x^3 / 24 + ...: the cubic term of the law's inverse
FINE_FACTOR = 1.1                        # the fine negative-control factor (decision 0006 decision 24; at L4 gains x 1.1
                                         # is J / 1.1, decision 0005): J x 1.1 is the controls' planted plant error
TEST_TORQUE_NM = 1e-3                    # the torque hook's test input: +-1 mN m on pitch, alternating per execution; any
                                         # nonzero value shows the hook enters both models identically


def _say(capsys, *lines):
    with capsys.disabled():
        print()
        for line in lines:
            print(line)


def _max_abs_diff(a, b):
    return max(abs(x - y) for x, y in zip(a, b))


def _tick_rule(x, divisor):
    return max(abs(x[k + 1] - x[k]) for k in range(len(x) - 1)) / divisor


def _rest_speeds(plant, thrust):
    """The rotor speeds of the zero-torque allocation of the thrust request (simulate's mixer: f_i = c M[i, thrust])."""
    return [math.sqrt(thrust * row[0] / plant.k) for row in plant.m]


@pytest.fixture(scope="module")
def ctx(rate_lead_design):
    with mock.patch.object(fe.rl, "design", return_value=rate_lead_design):
        c = fe.setup("none")
    step, sps = fe.step_plan(c["fixture"], L4 / "step_roll.yaml")
    doc = fe.run_l4.l2_scenario_doc(fe.run_l4.l4s.load(L4 / "step_roll.yaml"), step.plan, "step_roll", "test")
    p5, su = bd.l5_setup()
    j5 = tuple(p5[aor.INERTIA[a]] for a in aor.AXES)
    return {"c": c, "step": step, "sps": sps, "doc": doc, "p5": p5, "su": su, "j5": j5,
            "plant5": dataclasses.replace(c["plants"][0], inertia=j5, tau=p5["motor_tau"])}


# ---- (1) the corner rules -------------------------------------------------------------------------------------------

def test_gyro_bias_is_imu_corner_configs_rule():
    bound = bd.gic.imu_config(fe.PROFILE)[0]["gyro_turn_on_bias_bound"]
    assert bd.gyro_bias(GYRO_CORNER) == (bound, -bound, bound)
    assert bd.gyro_bias(ACCEL_CORNER) == (0.0, 0.0, 0.0)
    for bad in ((2, 0, 0, 0, 0, 0), (0, 0, 0, 0, 0), (True, 0, 0, 0, 0, 0)):
        with pytest.raises(ValueError):
            bd.gyro_bias(bad)


def test_clock_error_is_0012s_realised_outward_value(ctx):
    assert bd.clock_error(0, ctx["doc"]) == 0.0
    for corner, ppm in QE_PPM.items():
        assert abs(bd.clock_error(corner, ctx["doc"]) / PPM - ppm) <= QE_HALF_UNIT_PPM, corner


# ---- (2) the L4 mode is simulate --------------------------------------------------------------------------------------

def test_l4_mode_is_simulate_bit_for_bit(ctx):
    c = ctx["c"]
    law, sensor, plant, plan, sps = c["laws"]["PID+FF+lag"], c["sensors"]["T4e"], c["plants"][0], c["plan"], c["sps"]
    bias = bd.gyro_bias(GYRO_CORNER)
    e = bd.clock_error(1, ctx["doc"])
    n = plan.end_execution + 1
    torque = [[0.0] * n, [TEST_TORQUE_NM if k % 2 else -TEST_TORQUE_NM for k in range(n)], [0.0] * n]
    runs = []
    for kw in ({}, {"bias": bias, "clock_error": e, "torque": torque}):
        w, flagged = fe.simulate(law, sensor, plant, plan, sps, plan.thrust_n, **kw)
        res = bd.run(law, sensor, plant, plan, plan.thrust_n, setpoints=sps, **kw)
        assert res["w"] == w and res["flagged"] == flagged, sorted(kw)
        runs.append(w)
    assert runs[1] != runs[0]


def test_each_hook_acts_and_a_zero_bias_is_no_bias(ctx):
    c, step, sps = ctx["c"], ctx["step"], ctx["sps"]
    args = (c["laws"]["PID+FF+lag"], c["sensors"]["T4e"], c["plants"][0], step, sps, step.thrust_n)
    n = step.end_execution + 1
    off, _ = fe.simulate(*args)
    assert fe.simulate(*args, bias=(0.0, 0.0, 0.0))[0] == off
    for kw in ({"bias": bd.gyro_bias(GYRO_CORNER)}, {"clock_error": bd.clock_error(1, ctx["doc"])},
               {"torque": [[0.0] * n, [TEST_TORQUE_NM] * n, [0.0] * n]}):
        assert fe.simulate(*args, **kw)[0] != off, sorted(kw)


# ---- (3) the L5 mode reproduces recovery_model and the T3 oracle -------------------------------------------------------

def _l5_design(ctx, s=0.0, t=0.0):
    p, su = ctx["p5"], ctx["su"]
    return bd.DesignPlant(tuple(j * (1 + s * su.j_band) for j in ctx["j5"]), p["motor_tau"] * (1 + t * su.tau_band))


def _lpf(su):
    return fe.Sensor("the L5 oracle's chain low-pass", 0, (su.lpf,))


@pytest.mark.parametrize("scenario", ["recover_tumble", "recover_inverted"])
def test_l5_design_mode_is_recovery_model_bit_for_bit(ctx, scenario):
    su = ctx["su"]
    st = fe.schema.load_yaml(ROOT / "scenarios" / "quad" / "L05" / f"{scenario}.yaml")["initial_state"]
    q0, w0 = tuple(st["attitude_q_wxyz"]["value"]), tuple(st["body_rates_frd_rad_s"]["value"])
    n = RECOVERY_EXECUTIONS
    att = bd.Attitude(su.cfg, su.ratio, ((0.0, 0.0, 0.0),) * n)
    mine, refs = [], []
    for s, t in ((0.0, 0.0), BOX_MEMBER):
        refs.append(rm.member_run(su, s, t, q0, w0, n)[0])
        res = bd.run(bd.l5_law(ctx["p5"]), _lpf(su), _l5_design(ctx, s, t), bd.l5_plan(su, n, 0.0), 0.0, attitude=att,
                     q0=q0, w0=w0)
        mine.append([rm.channels(res["q"][k], [res["w"][a][k] for a in range(3)]) for k in range(n)])
        assert mine[-1] == refs[-1], (s, t)
    assert mine[0] != refs[1]  # control: the card member against the box corner's reference


@pytest.mark.parametrize("name, segment", [("step_roll", STEP_SEGMENT), ("yaw_release", YAW_SEGMENT)])
def test_l5_design_mode_is_the_t3_golden_bit_for_bit(ctx, name, segment):
    su = ctx["su"]
    gold = aor.simulate(su, name, segment)
    n_att = su.attitude_executions(segment)
    axis = aor.scenario_axis(name)
    sticks = tuple(aor.script_sticks(name, a, 1, 1 + segment) for a in range(n_att))
    for law in (bd.oracle_rate, None):
        res = bd.run(bd.l5_law(ctx["p5"]), _lpf(su), _l5_design(ctx), bd.l5_plan(su, n_att * su.ratio, 0.0), 0.0,
                     attitude=bd.Attitude(su.cfg, su.ratio, sticks, law))
        assert res["phi"][axis][::su.ratio] == gold["th"] and res["w"][axis][::su.ratio] == gold["om"], law
        if name == "yaw_release":
            assert gold["lock_a"] is not None
            lock = next(a for a in range(gold["a_r"], n_att) if res["phase"][a] == "locked")
            assert lock == gold["lock_a"]
    late = bd.Attitude(su.cfg, su.ratio, (sticks[0],) + sticks[:-1])  # control: the sticks one execution late
    res = bd.run(bd.l5_law(ctx["p5"]), _lpf(su), _l5_design(ctx), bd.l5_plan(su, n_att * su.ratio, 0.0), 0.0,
                 attitude=late)
    assert res["phi"][axis][::su.ratio] != gold["th"]


# ---- (4) the nonlinear plant against the design plant ----------------------------------------------------------------

def test_l5_nonlinear_plant_is_the_design_plant_within_one_tick(ctx, capsys):
    su, plant = ctx["su"], dataclasses.replace(ctx["plant5"], coupling=False)
    thrust = ctx["step"].thrust_n
    n_att = su.attitude_executions(L5_STEP_SEGMENT)
    att = bd.Attitude(su.cfg, su.ratio, tuple(aor.script_sticks("step_roll", a, 1, 1 + L5_STEP_SEGMENT)
                                              for a in range(n_att)))
    plan = bd.l5_plan(su, n_att * su.ratio, thrust)
    law = bd.l5_law(ctx["p5"])
    ref = bd.run(law, _lpf(su), _l5_design(ctx), plan, thrust, attitude=att)
    planted = bd.run(law, _lpf(su), dataclasses.replace(_l5_design(ctx), inertia=tuple(FINE_FACTOR * j for j in ctx["j5"])),
                     plan, thrust, attitude=att)
    res = bd.run(law, _lpf(su), plant, plan, thrust, attitude=att, rotor0=_rest_speeds(plant, thrust), dshot=bd.DSHOT_OFF)
    lines = []
    for key in ("phi", "w"):
        diff, rule = _max_abs_diff(res[key][0], ref[key][0]), _tick_rule(ref[key][0], su.divisor)
        ctl, ctl_rule = _max_abs_diff(res[key][0], planted[key][0]), _tick_rule(planted[key][0], su.divisor)
        lines.append(f"(4) L5 step_roll, {key} roll: max |NL - design| {diff:.3e}, one-tick rule {rule:.3e}; control "
                     f"J x {FINE_FACTOR}: {ctl:.3e} against {ctl_rule:.3e}")
        assert diff <= rule, key
        assert ctl > ctl_rule, key
    _say(capsys, *lines)


# ---- (5) check (i) at L4 --------------------------------------------------------------------------------------------

def _shifted(sps, bias):
    return [[x - b if k > 0 else x for k, x in enumerate(col)] for col, b in zip(sps, bias)]


def test_l4_bias_is_a_setpoint_offset_bit_for_bit_and_ff_breaks_it(ctx, capsys):
    c, step, sps = ctx["c"], ctx["step"], ctx["sps"]
    sensor, plant = c["sensors"]["T4e"], c["plants"][0]
    bias = bd.gyro_bias(GYRO_CORNER)
    out = {}
    for name in ("PID", "PID+FF+lag"):
        law = c["laws"][name]
        biased, _ = fe.simulate(law, sensor, plant, step, sps, step.thrust_n, bias=bias)
        offset, _ = fe.simulate(law, sensor, plant, step, _shifted(sps, bias), step.thrust_n)
        out[name] = (biased == offset, max(_max_abs_diff(x, y) for x, y in zip(biased, offset)))
    _say(capsys, f"(5 a) L4 step_roll, simulate(bias b) - simulate(setpoints - b): FF off max {out['PID'][1]:.3e}, "
                 f"FF on max {out['PID+FF+lag'][1]:.3e} rad/s")
    assert out["PID"][0]
    assert not out["PID+FF+lag"][0]


def test_l4_hold_delta_is_minus_b_s_within_one_tick(ctx, capsys):
    c, step = ctx["c"], ctx["step"]
    p = c["fixture"]
    law, sensor = c["laws"]["PID"], c["sensors"]["T4e"].linear
    plant = dataclasses.replace(c["plants"][0], inertia=tuple(p[k] for k in fe.INERTIA_KEYS), tau=p["motor_tau"],
                                coupling=False)
    n = step.end_execution + 1
    hold = [[0.0] * n for _ in range(3)]
    bias = bd.gyro_bias(GYRO_CORNER)
    kw = {"setpoints": hold, "rotor0": _rest_speeds(plant, step.thrust_n), "dshot": bd.DSHOT_OFF}
    biased = bd.run(law, sensor, plant, step, step.thrust_n, bias=bias, **kw)["w"]
    nominal = bd.run(law, sensor, plant, step, step.thrust_n, bias=(0.0, 0.0, 0.0), **kw)["w"]
    stamps = [step.stamp_us(k) for k in range(n)]
    lines = []
    def minus_b_s(a, j_scale):
        jt, tt = p[fe.INERTIA_KEYS[a]] * j_scale, p["motor_tau"]
        maps = (c["su"].plant_map(jt, tt), fe.tick_map(c["su1"], jt, tt))
        s = fe.linear_response(law.kp[a], law.ki[a], law.kd[a], law.tau_ref[a], law.d_tau[a], sensor, maps,
                               [0.0] + [1.0] * (n - 1), stamps, step.divisor)
        return [-bias[a] * x for x in s]

    for a in range(3):
        lin, planted = minus_b_s(a, 1.0), minus_b_s(a, FINE_FACTOR)
        delta = [x - y for x, y in zip(biased[a], nominal[a])]
        diff, rule = _max_abs_diff(delta, lin), _tick_rule(lin, step.divisor)
        ctl, ctl_rule = _max_abs_diff(delta, planted), _tick_rule(planted, step.divisor)
        lines.append(f"(5 b) L4 hold, axis {fe.AXES[a]}: max |delta - (-b s)| {diff:.3e} rad/s ({diff / abs(bias[a]):.2e} "
                     f"of |b|), one-tick rule {rule:.3e}; control J x {FINE_FACTOR}: {ctl:.3e} against {ctl_rule:.3e}")
        assert max(abs(x) for x in nominal[a]) == 0.0
        assert diff <= rule, a
        assert ctl > ctl_rule, a
    _say(capsys, *lines)


# ---- (6) check (i) at L5 --------------------------------------------------------------------------------------------

def _hold(ctx, n):
    su = ctx["su"]
    return bd.Attitude(su.cfg, su.ratio, ((0.0, 0.0, 0.0),) * n), bd.l5_plan(su, n * su.ratio, ctx["step"].thrust_n)


def _ff_law(ctx):
    ffl = ctx["c"]["laws"]["PID+FF+lag"]
    return bd.l5_law(ctx["p5"], ff=(ctx["j5"], ctx["p5"]["motor_tau"], ffl.ff_tau))


def test_l5_bias_is_a_rate_reference_offset_bit_for_bit_and_ff_breaks_it(ctx, capsys):
    su, plant, sensor = ctx["su"], ctx["plant5"], ctx["c"]["sensors"]["T4e"]
    n = L5_IDENTITY_EXECUTIONS
    sticks = tuple(aor.script_sticks("step_roll", a, 1, 1 + L5_STEP_SEGMENT) for a in range(n))
    att, plan = bd.Attitude(su.cfg, su.ratio, sticks), bd.l5_plan(su, n * su.ratio, ctx["step"].thrust_n)
    bias = bd.gyro_bias(GYRO_CORNER)
    offset = [[0.0] + [-b] * (n * su.ratio - 1) for b in bias]
    rotor0 = _rest_speeds(plant, plan.thrust_n)
    out = {}
    for name, law in (("FF off", bd.l5_law(ctx["p5"])), ("FF on", _ff_law(ctx))):
        a = bd.run(law, sensor, plant, plan, plan.thrust_n, attitude=att, rotor0=rotor0, bias=bias)
        b = bd.run(law, sensor, plant, plan, plan.thrust_n, attitude=att, rotor0=rotor0, rate_add=offset)
        out[name] = (a["w"] == b["w"] and a["q"] == b["q"], max(_max_abs_diff(x, y) for x, y in zip(a["w"], b["w"])))
    _say(capsys, f"(6 a) L5 step_roll, run(bias b) - run(rate_add -b), w: FF off max {out['FF off'][1]:.3e}, FF on max "
                 f"{out['FF on'][1]:.3e} rad/s")
    assert out["FF off"][0]
    assert not out["FF on"][0]


def offset_bound(r_end, b, kp):
    """|e_end - b / kp| for the single-axis law r = 2 kp sin(e / 2) (its yaw form has the smaller cubic): e_end =
    2 asin(r_end / (2 kp)), so the bound is |r_end - b| / (kp sqrt(1 - xi^2)) with xi = max(|r_end|, |b|) / (2 kp) (the mean
    value theorem) plus |2 asin(b / (2 kp)) - b / kp| <= |b / kp|^3 / 24 (1 - xi^2)^(-3/2) (Taylor's remainder)."""
    xi = max(abs(r_end), abs(b)) / (2 * kp)
    return abs(r_end - b) / (kp * math.sqrt(1 - xi * xi)) + abs(b / kp) ** 3 / TAYLOR_DIVISOR / (1 - xi * xi) ** 1.5


def test_l5_hold_offset_is_b_over_att_kp(ctx, capsys):
    su = ctx["su"]
    plant = dataclasses.replace(ctx["plant5"], coupling=False)
    att, plan = _hold(ctx, HOLD_EXECUTIONS)
    kw = {"attitude": att, "rotor0": _rest_speeds(plant, plan.thrust_n), "dshot": bd.DSHOT_OFF}
    law = bd.l5_law(ctx["p5"])
    nominal = bd.run(law, _lpf(su), plant, plan, plan.thrust_n, bias=(0.0, 0.0, 0.0), **kw)
    assert all(x == 0.0 for col in nominal["w"] for x in col) and all(q == bd.IDENTITY for q in nominal["q"])
    kp = su.cfg.kp
    lines = []
    for a in HOLD_AXES:
        signs = tuple(1 if i == a else 0 for i in range(6))
        b = bd.gyro_bias(signs)[a]
        res = bd.run(law, _lpf(su), plant, plan, plan.thrust_n, bias=bd.gyro_bias(signs), **kw)
        err = rm.channels(res["q"][-1], [res["w"][i][-1] for i in range(3)])
        r_end = rm.law(su.cfg, res["q"][-1], bd.IDENTITY)[a]
        bound = offset_bound(r_end, b, kp)
        lines.append(f"(6 b) L5 hold, gyro {fe.AXES[a]} +bound: delta err at the end {err[a]:.9e}, b / att_kp "
                     f"{b / kp:.9e}, difference {err[a] - b / kp:+.3e} (bound {bound:.3e}; r_end - b {r_end - b:+.3e})")
        assert abs(err[a] - b / kp) <= bound, a
        assert abs(err[a] - b / (FINE_FACTOR * kp)) > bound, a  # control: att_kp x 1.1
        assert all(err[i] == 0.0 for i in range(3) if i != a)
    _say(capsys, *lines)


# ---- (7) check (ii) and its control ----------------------------------------------------------------------------------

def test_l4_accel_only_corner_gives_zero_delta_and_a_gyro_flip_changes_it(ctx, capsys):
    c, step, sps, doc = ctx["c"], ctx["step"], ctx["sps"], ctx["doc"]
    args = (c["laws"]["PID+FF+lag"], c["sensors"]["T4e"], c["plants"][0], step, sps)
    accel = bd.l4_delta(*args, bd.Corner(ACCEL_CORNER), doc)
    assert all(x == 0.0 for col in accel for x in col)
    gyro = bd.l4_delta(*args, bd.Corner(GYRO_CORNER), doc)
    flipped = bd.l4_delta(*args, bd.Corner(FLIPPED_CORNER), doc)
    _say(capsys, "(7) L4 step_roll max |delta| per axis: gyro corner "
         + " ".join(f"{max(abs(x) for x in col):.3e}" for col in gyro) + "; x flipped "
         + " ".join(f"{max(abs(x) for x in col):.3e}" for col in flipped) + " rad/s")
    assert gyro != flipped
    assert any(x != 0.0 for x in gyro[0])


def test_l5_accel_only_corner_gives_zero_delta_and_a_gyro_flip_changes_it(ctx, capsys):
    su, plant, doc = ctx["su"], ctx["plant5"], ctx["doc"]
    n = L5_IDENTITY_EXECUTIONS
    sticks = tuple(aor.script_sticks("step_roll", a, 1, 1 + L5_STEP_SEGMENT) for a in range(n))
    att, plan = bd.Attitude(su.cfg, su.ratio, sticks), bd.l5_plan(su, n * su.ratio, ctx["step"].thrust_n)
    args = (_ff_law(ctx), ctx["c"]["sensors"]["T4e"], plant, plan, att)
    kw = {"rotor0": _rest_speeds(plant, plan.thrust_n)}
    accel = bd.l5_delta(*args, bd.Corner(ACCEL_CORNER), doc, **kw)
    assert all(x == 0.0 for col in accel for x in col)
    gyro = bd.l5_delta(*args, bd.Corner(GYRO_CORNER), doc, **kw)
    flipped = bd.l5_delta(*args, bd.Corner(FLIPPED_CORNER), doc, **kw)
    _say(capsys, "(7) L5 step_roll max |delta| per channel (" + " ".join(rm.CHANNELS) + "): gyro corner "
         + " ".join(f"{max(abs(x) for x in col):.3e}" for col in gyro) + "; x flipped "
         + " ".join(f"{max(abs(x) for x in col):.3e}" for col in flipped))
    assert gyro != flipped
    assert any(x != 0.0 for x in gyro[0])
